### ISSUE TITLE
Weight and Dataset Download Links Request

### ISSUE THREAD

**Issue by SHUzhekiNg** [GigaAI-research/ReconDreamer#2]
Hi, thank you for your amazing work!
Would you please upload the weight and dataset to Google Drive? Thanks！

**Comment by GigaAI-research** [comment]
Thank you for your attention! This is the link [Dataset and weight](https://drive.google.com/file/d/1MLX6SIVTaQuhsDC9UKzjWw8eNn7zsvgJ/view?usp=sharing).
